### ISSUE TITLE
Replace 'new Instruction' with constants for cases where inputs will always be the same to reduce memory alloc

### ISSUE THREAD

**Issue by Col-E** [Col-E/r8#6]
Things like `CfThrow` and `CfReturn` have no parameters. Having multiple instances in memory is a waste.

**Comment by xxDark** [comment]
Partially done, we might want to also cache common scenarios for register loads and stores. E.g. `ALOAD 0`, `XLOAD 0-5` probably appear often in the resulting bytecode. Same for any stack operation (`POP`, `POP2`, `SWAP`, etc).

**Comment by Col-E** [comment]
Basically all the CF instructions that _can_ be reasonably cached are now cached.

None of the DEX instructions can be cached due to their linked `int offset` value that is used frequently. Calling this done.
